// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace RentalService.Infrastructure
{
    partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var rental = RentalEntityType.Create(this);

            RentalEntityType.CreateAnnotations(rental);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
